### ISSUE TITLE
Lettre manquante dans la description d'un événement ?

### ISSUE THREAD

**Issue by Elmer-A** [capitoledulibre/2018.capitoledulibre.org#8]
Sur https://2018.capitoledulibre.org/programme/#la-place-des-gull-dans-le-monde-du-libre

"Après avoir organisé une journée inter-gull, le 10 juillet 2018, aux Rencontres Mondiales du Logiciel Libre, à Strasbourg, l'April, ***ramasoft*** et Montpel'libre [...]"
&rArr; **F**ramasoft, sauf erreur ?

**Comment by simon-previdente** [comment]
C'est corrigé, merci :)
